name: Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Decode release keystore
        run: echo "${{ secrets.URL_SHORTENER_KEY }}" | base64 --decode > app/url-shortener.keystore

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/outputs/apk/release/app-release.apk
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          body: |
            Automatic APK build.
            - Version: ${{ github.ref_name }}
